function getVariantLatte(name, accent){
	return {
		colors: {
			toolbar: "#eff1f5",
			toolbar_text: "#4c4f69",
			frame: "#dce0e8",
			tab_background_text: "#4c4f69",
			toolbar_field: "#e6e9ef",
			toolbar_field_text: "#4c4f69",
			tab_line: accent,
			popup: "#eff1f5",
			popup_text: "#4c4f69",
			button_background_active: "#9ca0b0",
			frame_inactive: "#dce0e8",
			icons_attention: accent,
			icons: accent,
			ntp_background: "#dce0e8",
			ntp_text: "#4c4f69",
			popup_border: accent,
			popup_highlight_text: "#4c4f69",
			popup_highlight: "#9ca0b0",
			sidebar_border: accent,
			sidebar_highlight_text: "#dce0e8",
			sidebar_highlight: accent,
			sidebar_text: "#4c4f69",
			sidebar: "#eff1f5",
			tab_background_separator: accent,
			tab_loading: accent,
			tab_selected: "#eff1f5",
			tab_text: "#4c4f69",
			toolbar_bottom_separator: accent,
			toolbar_field_border_focus: accent,
			toolbar_field_border: "#eff1f5",
			toolbar_field_focus: "#eff1f5",
			toolbar_field_highlight_text: "#eff1f5",
			toolbar_field_highlight: accent,
			toolbar_field_separator: accent,
			toolbar_vertical_separator: accent,
		},
		properties: {
        color_scheme: "system"
    },
		title: `Latte ${name}`,
	}
}

function getVariantFrappe(name, accent){
	return {
		colors: {
			toolbar: "#303446",
			toolbar_text: "#c6d0f5",
			frame: "#232634",
			tab_background_text: "#c6d0f5",
			toolbar_field: "#292c3c",
			toolbar_field_text: "#c6d0f5",
			tab_line: accent,
			popup: "#303446",
			popup_text: "#c6d0f5",
			button_background_active: "#737994",
			frame_inactive: "#232634",
			icons_attention: accent,
			icons: accent,
			ntp_background: "#232634",
			ntp_text: "#c6d0f5",
			popup_border: accent,
			popup_highlight_text: "#c6d0f5",
			popup_highlight: "#737994",
			sidebar_border: accent,
			sidebar_highlight_text: "#232634",
			sidebar_highlight: accent,
			sidebar_text: "#c6d0f5",
			sidebar: "#303446",
			tab_background_separator: accent,
			tab_loading: accent,
			tab_selected: "#303446",
			tab_text: "#c6d0f5",
			toolbar_bottom_separator: accent,
			toolbar_field_border_focus: accent,
			toolbar_field_border: "#303446",
			toolbar_field_focus: "#303446",
			toolbar_field_highlight_text: "#303446",
			toolbar_field_highlight: accent,
			toolbar_field_separator: accent,
			toolbar_vertical_separator: accent,
		},
		properties: {
        color_scheme: "system"
    },
		title: `Frappe ${name}`,
	}
}

function getVariantMacchiato(name, accent){
	return {
		colors: {
			toolbar: "#24273a",
			toolbar_text: "#cad3f5",
			frame: "#181926",
			tab_background_text: "#cad3f5",
			toolbar_field: "#1e2030",
			toolbar_field_text: "#cad3f5",
			tab_line: accent,
			popup: "#24273a",
			popup_text: "#cad3f5",
			button_background_active: "#6e738d",
			frame_inactive: "#181926",
			icons_attention: accent,
			icons: accent,
			ntp_background: "#181926",
			ntp_text: "#cad3f5",
			popup_border: accent,
			popup_highlight_text: "#cad3f5",
			popup_highlight: "#6e738d",
			sidebar_border: accent,
			sidebar_highlight_text: "#181926",
			sidebar_highlight: accent,
			sidebar_text: "#cad3f5",
			sidebar: "#24273a",
			tab_background_separator: accent,
			tab_loading: accent,
			tab_selected: "#24273a",
			tab_text: "#cad3f5",
			toolbar_bottom_separator: accent,
			toolbar_field_border_focus: accent,
			toolbar_field_border: "#24273a",
			toolbar_field_focus: "#24273a",
			toolbar_field_highlight_text: "#24273a",
			toolbar_field_highlight: accent,
			toolbar_field_separator: accent,
			toolbar_vertical_separator: accent,
		},
		properties: {
        color_scheme: "system"
    },
		title: `Macchiato ${name}`,
	}
}



function getVariantMocha(name, accent){
	return {
		colors: {
			toolbar: "#1e1e2e",
			toolbar_text: "#cdd6f4",
			frame: "#11111b",
			tab_background_text: "#cdd6f4",
			toolbar_field: "#181825",
			toolbar_field_text: "#cdd6f4",
			tab_line: accent,
			popup: "#1e1e2e",
			popup_text: "#cdd6f4",
			button_background_active: "#6c7086",
			frame_inactive: "#11111b",
			icons_attention: accent,
			icons: accent,
			ntp_background: "#11111b",
			ntp_text: "#cdd6f4",
			popup_border: accent,
			popup_highlight_text: "#cdd6f4",
			popup_highlight: "#6c7086",
			sidebar_border: accent,
			sidebar_highlight_text: "#11111b",
			sidebar_highlight: accent,
			sidebar_text: "#cdd6f4",
			sidebar: "#1e1e2e",
			tab_background_separator: accent,
			tab_loading: accent,
			tab_selected: "#1e1e2e",
			tab_text: "#cdd6f4",
			toolbar_bottom_separator: accent,
			toolbar_field_border_focus: accent,
			toolbar_field_border: "#1e1e2e",
			toolbar_field_focus: "#1e1e2e",
			toolbar_field_highlight_text: "#1e1e2e",
			toolbar_field_highlight: accent,
			toolbar_field_separator: accent,
			toolbar_vertical_separator: accent,
		},
		properties: {
        color_scheme: "system"
    },
		title: `Mocha ${name}`,
	}
}

export default [
	getVariantLatte("rosewater", "#dc8a78"),
	getVariantLatte("flamingo", "#dd7878"),
	getVariantLatte("pink", "#ea76cb"),
	getVariantLatte("mauve", "#8839ef"),
	getVariantLatte("red", "#d20f39"),
	getVariantLatte("maroon", "#e64553"),
	getVariantLatte("peach", "#fe640b"),
	getVariantLatte("yellow", "#df8e1d"),
	getVariantLatte("green", "#40a02b"),
	getVariantLatte("teal", "#179299"),
	getVariantLatte("sky", "#04a5e5"),
	getVariantLatte("sapphire", "#209fb5"),
	getVariantLatte("blue", "#1e66f5"),
	getVariantLatte("lavender", "#7287fd"),

	getVariantFrappe("rosewater", "#f2d5cf"),
	getVariantFrappe("flamingo", "#eebebe"),
	getVariantFrappe("pink", "#f4b8e4"),
	getVariantFrappe("mauve", "#ca9ee6"),
	getVariantFrappe("red", "#e78284"),
	getVariantFrappe("maroon", "#ea999c"),
	getVariantFrappe("peach", "#ef9f76"),
	getVariantFrappe("yellow", "#e5c890"),
	getVariantFrappe("green", "#a6d189"),
	getVariantFrappe("teal", "#81c8be"),
	getVariantFrappe("sky", "#99d1db"),
	getVariantFrappe("sapphire", "#85c1dc"),
	getVariantFrappe("blue", "#8caaee"),
	getVariantFrappe("lavender", "#babbf1"),

	getVariantMacchiato("rosewater", "#f4dbd6"),
	getVariantMacchiato("flamingo", "#f0c6c6"),
	getVariantMacchiato("pink", "#f5bde6"),
	getVariantMacchiato("mauve", "#c6a0f6"),
	getVariantMacchiato("red", "#ed8796"),
	getVariantMacchiato("maroon", "#ee99a0"),
	getVariantMacchiato("peach", "#f5a97f"),
	getVariantMacchiato("yellow", "#eed49f"),
	getVariantMacchiato("green", "#a6da95"),
	getVariantMacchiato("teal", "#8bd5ca"),
	getVariantMacchiato("sky", "#91d7e3"),
	getVariantMacchiato("sapphire", "#7dc4e4"),
	getVariantMacchiato("blue", "#8aadf4"),
	getVariantMacchiato("lavender", "#b7bdf8"),

	getVariantMocha("rosewater", "#f5e0dc"),
	getVariantMocha("flamingo", "#f2cdcd"),
	getVariantMocha("pink", "#f5c2e7"),
	getVariantMocha("mauve", "#cba6f7"),
	getVariantMocha("red", "#f38ba8"),
	getVariantMocha("maroon", "#eba0ac"),
	getVariantMocha("peach", "#fab387"),
	getVariantMocha("yellow", "#f9e2af"),
	getVariantMocha("green", "#a6e3a1"),
	getVariantMocha("teal", "#94e2d5"),
	getVariantMocha("sky", "#89dceb"),
	getVariantMocha("sapphire", "#74c7ec"),
	getVariantMocha("blue", "#89b4fa"),
	getVariantMocha("lavender", "#b4befe"),
]
